services:
  quiz:
    build:
      context: .
      dockerfile: ./apps/quiz/Dockerfile
    image: ramadhanialqadri12/quiz-app.quiz:latest
    env_file:
      - ./apps/quiz/.env
    depends_on:
      # - mongodb
      - rabbitmq
      - mongodb
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  grading:
    build:
      context: .
      dockerfile: ./apps/grading/Dockerfile
    image: ramadhanialqadri12/quiz-app.grading:latest
    env_file:
      - ./apps/grading/.env
    depends_on:
      - mongodb
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    image: ramadhanialqadri12/quiz-app.auth:latest
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: