apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /quiz
            pathType: Prefix
            backend:
              service:
                name: quiz
                port:
                  number: 3000
          - path: /grading
            pathType: Prefix
            backend:
              service:
                name: grading
                port:
                  number: 3001
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3002
