apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grading
  template:
    metadata:
      labels:
        app: grading
    spec:
      containers:
        - name: grading
          image: dwf19/quiz-app_grading
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: RABBIT_MQ_QUIZ_QUEUE
              value: quiz
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: MONGODB_URI
              value: mongodb://root:password123@quiz-app-mongodb-headless:27017/
            - name: RABBIT_MQ_URI
              value: amqp://user1:password123@quiz-app-rabbitmq:5672
