apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      containers:
        - name: quiz
          image: dwf19/quiz-app_quiz
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: RABBIT_MQ_QUIZ_QUEUE
              value: quiz
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: MONGODB_URI
              value: mongodb://root:password123@quiz-app-mongodb-headless:27017/
            - name: RABBIT_MQ_URI
              value: amqp://user1:password123@quiz-app-rabbitmq:5672